/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * plan 생성 + 계산
         * @description Kan-9 §2 정적 검증 → 현재 스냅샷 로드 → plan·inv_account·inv_holding 저장(한 트랜잭션) → ai-service POST /calculate (본문 = 요청 dict 그대로, 타임아웃 10초) → 201.
         *
         *     계산 실패 시 plan 은 저장된 채 502 CALCULATION_FAILED (retryable, public_id 동봉).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Kan-9 §2 입력 8필드 (v0.2). v0.3 필드가 있으면 400 UNSUPPORTED_FIELD */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanInputs"];
                };
            };
            responses: {
                /** @description plan + calculation (analyze() 출력 그대로) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanResponse"];
                    };
                };
                /** @description 입력 검증 실패 (여러 건을 errors[] 로 한 번에) · v0.3 필드 · 데이터 의존 오류 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description ai-service 스냅샷과 DB data_snapshot(is_current) 불일치 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 계산 실패. plan 은 저장됨 → GET /plans/{public_id} 로 재시도 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * plan 재조회 = 재계산
         * @description 저장된 inputs 로 다시 계산한다(결과 저장 없음). 새로고침·공유 링크 대응. 본문은 POST /plans 와 동일.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description POST /plans 응답의 plan.public_id */
                    public_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanResponse"];
                    };
                };
                /** @description PLAN_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description CALCULATION_FAILED */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{public_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 설명 (결과 화면과 분리해서 나중에 채운다)
         * @description 재계산 → analyze() 출력 + rebalancing.focus + goal.amount → ai-service POST /rag/answer (타임아웃 30초).
         *
         *     ai-service 규약대로 **처리가 끝나면 항상 200**, 성패는 `status`. 결과 화면은 그대로 두고 설명 영역만 바꾼다. ai-service 불가·타임아웃만 502 EXPLANATION_UNAVAILABLE (retryable).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description POST /plans 응답의 plan.public_id */
                    public_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description status 로 분기. OK 면 explanation, 아니면 message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExplanationResponse"];
                    };
                };
                /** @description PLAN_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description ai-service 불가·타임아웃 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{public_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 단발 질문 (KAN-24, 9/5 도윤 구두 확인)
         * @description 재계산 → analyze() 출력 + rebalancing.focus + goal.amount + question → ai-service POST /rag/ask (타임아웃 30초). 이력 없음 — 매 호출이 독립, 대화 저장 안 함.
         *
         *     ai-service 규약대로 **처리가 끝나면 항상 200**, 성패는 `status`. ai-service 불가·타임아웃만 502 ANSWER_UNAVAILABLE (retryable).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description POST /plans 응답의 plan.public_id */
                    public_id: string;
                };
                cookie?: never;
            };
            /** @description 자유 질문 텍스트 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuestionRequest"];
                };
            };
            responses: {
                /** @description status 로 분기. OK 면 answer, 아니면 message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionResponse"];
                    };
                };
                /** @description PLAN_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description ai-service 불가·타임아웃 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 입력 폼 자산 선택지 + 데이터 기준
         * @description data_snapshot(is_current) + 카탈로그. group=base 3종은 항상, optional(US_EQ_KR)은 카탈로그에 있을 때.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniverseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 대표 페르소나 입력값 (PRD 수용기준 5 · KAN-14)
         * @description 로그인 없이 샘플로 재현. inputs 를 그대로 POST /plans 에 보내면 된다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SamplesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdjustableInput
         * @description 사용자가 입력으로 조정할 수 있는 것 (KAN-9 §2 입력 필드). 이것만 다음 행동이 될 수 있다.
         *
         *     포트폴리오 비중 조정은 뺀다 — 권유하는 순간 투자자문이 된다.
         * @enum {string}
         */
        AdjustableInput: "MONTHLY_CONTRIBUTION" | "GOAL_HORIZON" | "GOAL_AMOUNT" | "ALLOC_MONTHLY" | "ALLOC_INITIAL" | "REBALANCING_FOCUS";
        /** Alloc */
        Alloc: {
            /** @description 합 100 아니면 ALLOC_SUM_INITIAL */
            initial: components["schemas"]["AllocSplit"];
            /** @description 합 100 아니면 ALLOC_SUM_MONTHLY */
            monthly: components["schemas"]["AllocSplit"];
        };
        /**
         * AllocSplit
         * @description 자금 배분율. 정수 퍼센트, 합 100. '투자 성향' 입력은 없고 이 배분율에서 파생된다 (Kan-9 확정 ⑪).
         */
        AllocSplit: {
            /** Invest */
            invest: number;
            /** Safe */
            safe: number;
            /** Other */
            other: number;
        };
        /** AssetUsed */
        AssetUsed: {
            /** Code */
            code: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Instrument
             * @default
             */
            instrument: string;
            /**
             * Tax Class
             * @default
             */
            tax_class: string;
        };
        /** AssetWeight */
        AssetWeight: {
            /**
             * Code
             * @description Kan-9 카탈로그 코드 (KR_EQ · US_EQ · KR_BOND · US_EQ_KR). 밖이면 ASSET_NOT_IN_CATALOG
             */
            code: string;
            /**
             * Weight
             * @description 정수 퍼센트. 0 < w ≤ 100 아니면 PORTFOLIO_WEIGHT_RANGE
             */
            weight: number;
        };
        /**
         * Calculation
         * @description ai-service POST /calculate 응답 = KAN-11 analyze() 출력 그대로 (Kan-9 §5). 백엔드는 가공·저장하지 않는다.
         *
         *     `schema.SimulationInput` 과 같은 모양에서 `focus`·`goal_amount` 만 없다 — 그 둘은 Spring이
         *     POST /rag/answer 를 부를 때 덧붙이는 값이라 공개 응답에는 나오지 않는다.
         */
        Calculation: {
            /**
             * Status
             * @default OK
             */
            status: string;
            meta: components["schemas"]["Meta"];
            derived?: components["schemas"]["Derived"];
            /** Per Period */
            per_period: {
                [key: string]: components["schemas"]["PeriodResult"];
            };
        };
        /** Claim */
        Claim: {
            /**
             * Text
             * @description 사용자에게 보여줄 문장
             */
            text: string;
            /**
             * Evidence
             * @description 이 문장에 등장한 모든 수치의 출처. 입력 JSON의 JSON Pointer (예: /per_period/Q/gap/shortfall) 또는 지식 청크 참조(chunk:<source_id>#<idx>). 근거를 댈 수 없는 숫자는 문장에서 뺄 것
             */
            evidence: string[];
        };
        /** Derived */
        Derived: {
            /**
             * Propensity Label
             * @default
             */
            propensity_label: string;
            /**
             * Invest Share Overall Pct
             * @default null
             */
            invest_share_overall_pct: number | null;
            /**
             * Plan Excluded Amount
             * @default null
             */
            plan_excluded_amount: number | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Kan-9 정적 검증 코드 (GOAL_AMOUNT_RANGE, WEIGHTS_SUM, …)
             */
            code: string;
            /**
             * Field
             * @description 점 표기 경로 (portfolio.assets)
             * @default null
             */
            field: string | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorEnvelope
         * @description 모든 4xx/5xx 의 본문. 프론트는 `code` 와 `retryable` 로만 분기한다.
         *
         *     입력 검증은 Kan-9 정적 오류 여러 개를 한 번에 돌려준다 — 봉투 `code=VALIDATION_ERROR`, 낱개는 `errors[]`
         *     (엔진 `ValidationError.errors` 와 같은 모양). 봉투를 유지하는 이유: 오류 응답의 최상위 모양이 항상 같아야
         *     프론트가 배열/객체를 분기하지 않는다.
         */
        ErrorEnvelope: {
            /**
             * Code
             * @description HTTP 층: VALIDATION_ERROR · UNSUPPORTED_FIELD · PLAN_NOT_FOUND · CALCULATION_FAILED · EXPLANATION_UNAVAILABLE · ANSWER_UNAVAILABLE · SNAPSHOT_MISMATCH. 데이터 의존 오류는 엔진 코드 그대로: INSUFFICIENT_HISTORY · ASSET_NOT_IN_CATALOG
             */
            code: string;
            /**
             * Message
             * @description 사용자에게 보여도 되는 문구
             */
            message: string;
            /**
             * Retryable
             * @description true = 재시도 버튼, false = 입력 수정 요구
             */
            retryable: boolean;
            /**
             * Field
             * @description 단일 필드 오류일 때 (UNSUPPORTED_FIELD 등)
             * @default null
             */
            field: string | null;
            /**
             * Errors
             * @description VALIDATION_ERROR 일 때 낱개 목록
             */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Public Id
             * @description CALCULATION_FAILED: plan은 저장됐으므로 재시도 = GET /plans/{public_id}
             * @default null
             */
            public_id: string | null;
            /**
             * Max Months
             * @description INSUFFICIENT_HISTORY 일 때 가능한 최대 기간
             * @default null
             */
            max_months: number | null;
        };
        /**
         * Explanation
         * @description AI 설명 응답. KAN-9 §7 필드 + evidence(KAN-12 추가) + highlighted_period(PRD 수용기준 4).
         */
        Explanation: {
            /** @description 2~3문장. 목표 간극과 전체 상황. 기준 구간(meta.window)을 반드시 언급 */
            summary: components["schemas"]["Claim"];
            /**
             * Per Period Pros Cons
             * @description M·Q·H 세 주기 전부. 각 장점≥1·단점≥1
             */
            per_period_pros_cons: {
                [key: string]: components["schemas"]["ProsCons"];
            };
            /**
             * Risks
             * @description ≥1. risk 지표 인용, MDD 1순위
             */
            risks: components["schemas"]["RiskClaim"][];
            /**
             * Next Actions
             * @description ≥1. 입력으로 조정 가능한 행동만
             */
            next_actions: components["schemas"]["NextAction"][];
            /** @description 기준 구간 + 환노출 + meta.data_basis 명시 */
            assumptions_note: components["schemas"]["Claim"];
            /** @description 입력 focus를 그대로 에코. focus가 없으면 null */
            highlighted_period: components["schemas"]["Period"] | null;
            /**
             * Retrieved Refs
             * @description 인용한 지식 청크 참조의 합집합. evidence의 chunk: 접두어를 뺀 <source_id>#<idx> 형식 (예: concept/max_drawdown#0). RAG 미사용 시 빈 배열
             */
            retrieved_refs: string[];
        };
        /**
         * ExplanationResponse
         * @description POST /plans/{public_id}/explanation 200 본문. 항상 200이고 성패는 `status` (KAN-17 규약 그대로).
         *
         *     ai-service 응답에서 `explanation`·`status`·`message` 만 노출한다. `attempts`·`violations`·`retrieved_refs` 는
         *     디버깅·저장용(agent_message)이라 브라우저에 주지 않는다.
         */
        ExplanationResponse: {
            status: components["schemas"]["ExplanationStatus"];
            /** @description status=OK 일 때만 non-null */
            explanation: components["schemas"]["Explanation"] | null;
            /**
             * Message
             * @description status≠OK 일 때 설명 영역에 보여줄 문구
             * @default null
             */
            message: string | null;
        };
        /**
         * ExplanationStatus
         * @enum {string}
         */
        ExplanationStatus: "OK" | "EXPLANATION_REJECTED" | "EXPLANATION_UNAVAILABLE";
        /** Funds */
        Funds: {
            /**
             * Initial
             * @description 초기 투자금 KRW. 음수 → FUNDS_INITIAL_RANGE
             */
            initial: number;
            /**
             * Monthly
             * @description 월 납입액 KRW (상수). 음수 → FUNDS_MONTHLY_RANGE. initial·monthly 동시 0 → NO_FUNDS
             */
            monthly: number;
        };
        /** Gap */
        Gap: {
            /** Fv Total */
            fv_total: number;
            /** Shortfall */
            shortfall: number;
            /**
             * Extra Monthly Required
             * @default null
             */
            extra_monthly_required: number | null;
            /**
             * Months Extension
             * @default null
             */
            months_extension: number | null;
            /**
             * Months Extension Raw
             * @default null
             */
            months_extension_raw: number | null;
            /**
             * Extension Status
             * @default null
             */
            extension_status: string | null;
            /**
             * Extra Monthly Ratio
             * @default null
             */
            extra_monthly_ratio: number | null;
            /**
             * Status
             * @default null
             */
            status: string | null;
            /**
             * Basis
             * @default null
             */
            basis: string | null;
            /**
             * Delta M Model
             * @default null
             */
            delta_m_model: string | null;
        };
        /** Goal */
        Goal: {
            /**
             * Amount
             * @description 목표 금액 KRW. 범위 밖 → GOAL_AMOUNT_RANGE
             */
            amount: number;
            /**
             * Horizon Months
             * @description 목표 기간(개월). 범위 밖 → GOAL_HORIZON_RANGE
             */
            horizon_months: number;
        };
        /** Meta */
        Meta: {
            /**
             * Assumptions Version
             * @default
             */
            assumptions_version: string;
            /**
             * Data Version
             * @default
             */
            data_version: string;
            /**
             * Data Hash
             * @default
             */
            data_hash: string;
            window: components["schemas"]["Window"];
            /** Assets Used */
            assets_used?: components["schemas"]["AssetUsed"][];
            /**
             * Data Basis
             * @default
             */
            data_basis: string;
            /**
             * Generated At
             * @default
             */
            generated_at: string;
            /**
             * Safe Rate Annual Pct
             * @default null
             */
            safe_rate_annual_pct: number | null;
            /** Warnings */
            warnings?: string[];
            /**
             * Start Month
             * @default
             */
            start_month: string;
            /**
             * Target Month
             * @default
             */
            target_month: string;
            /**
             * Cashflow Source
             * @default
             */
            cashflow_source: string;
            /** Series Used */
            series_used?: string[];
            /**
             * Options
             * @default null
             */
            options: {
                [key: string]: unknown;
            } | null;
        };
        /** NextAction */
        NextAction: {
            /** @description 조정 대상. 상품·종목·비중은 선택지에 없다 */
            adjustable_input: components["schemas"]["AdjustableInput"];
            /** Text */
            text: string;
            /** Evidence */
            evidence: string[];
        };
        /**
         * Period
         * @description 리밸런싱 주기. KAN-9 표기 M / Q / H.
         * @enum {string}
         */
        Period: "M" | "Q" | "H";
        /** PeriodResult */
        PeriodResult: {
            /** Trajectory */
            trajectory?: components["schemas"]["TrajectoryPoint"][];
            /** Cum Cost */
            cum_cost: number;
            risk: components["schemas"]["Risk"];
            gap: components["schemas"]["Gap"];
            /** @default null */
            tax: components["schemas"]["Tax"] | null;
        };
        /**
         * Plan
         * @description 저장된 입력 + 식별자. 백엔드가 채운다. 결과는 저장하지 않으므로 재조회 = 재계산.
         */
        Plan: {
            /**
             * Public Id
             * @description UUID. 조건 수정은 새 plan 생성(9/7 PUT 없음)
             */
            public_id: string;
            /**
             * Data Snapshot Id
             * @description 생성 시점 data_snapshot(is_current)
             */
            data_snapshot_id: number;
            /**
             * Created At
             * @description ISO 8601
             */
            created_at: string;
            inputs: components["schemas"]["PlanInputs"];
        };
        /**
         * PlanInputs
         * @description POST /plans 요청 본문 = Kan-9 §2 입력 dict 그대로. Spring은 변환 없이 ai-service POST /calculate 에 넘긴다.
         */
        PlanInputs: {
            goal: components["schemas"]["Goal"];
            funds: components["schemas"]["Funds"];
            alloc: components["schemas"]["Alloc"];
            portfolio: components["schemas"]["Portfolio"];
            rebalancing: components["schemas"]["Rebalancing"];
        };
        /**
         * PlanResponse
         * @description POST /plans 201 · GET /plans/{public_id} 200 공통 본문.
         */
        PlanResponse: {
            plan: components["schemas"]["Plan"];
            calculation: components["schemas"]["Calculation"];
        };
        /** Portfolio */
        Portfolio: {
            /**
             * Assets
             * @description 1~3개, weight 합 100 (WEIGHTS_SUM), code 중복 불가 (PORTFOLIO_ASSET_DUP)
             */
            assets: components["schemas"]["AssetWeight"][];
        };
        /** ProsCons */
        ProsCons: {
            /**
             * Pros
             * @description 이 주기의 장점. 비용·이탈·MDD 축으로 수치 인용
             */
            pros: components["schemas"]["Claim"][];
            /**
             * Cons
             * @description 이 주기의 단점. 우열 판정 금지
             */
            cons: components["schemas"]["Claim"][];
        };
        /**
         * QuestionHistoryItem
         * @description 세션 내 이전 질문·답변 한 쌍. 서버는 저장하지 않으므로 호출부(Spring/프론트)가 들고 있다가 매번 동봉한다.
         */
        QuestionHistoryItem: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /**
         * QuestionRequest
         * @description POST /plans/{public_id}/questions 요청 본문. 서버는 세션을 저장하지 않는다(대화 저장 안 함) —
         *     멀티턴이 되려면 history에 이전 질문·답변을 그대로 실어 보낸다. 비어 있으면 단발 질문과 동일하게 동작.
         */
        QuestionRequest: {
            /**
             * Question
             * @description 자유 질문 텍스트
             */
            question: string;
            /**
             * History
             * @description 이 세션에서 지금까지의 질문·답변. 빈 배열이면 단발 질문(이전 대화 없음)과 동일
             */
            history?: components["schemas"]["QuestionHistoryItem"][];
        };
        /**
         * QuestionResponse
         * @description POST /plans/{public_id}/questions 200 본문. ExplanationResponse와 같은 모양(status로 분기).
         *
         *     ai-service POST /rag/ask 의 answer(schema.Claim) 그대로 노출. attempts·retrieved_refs·violations는
         *     디버깅·저장용(agent_message, KAN-24)이라 브라우저에 주지 않는다 — ExplanationResponse와 동일한 원칙.
         */
        QuestionResponse: {
            status: components["schemas"]["QuestionStatus"];
            /** @description status=OK 일 때만 non-null */
            answer: components["schemas"]["Claim"] | null;
            /**
             * Message
             * @description status≠OK 일 때 답변 영역에 보여줄 문구
             * @default null
             */
            message: string | null;
        };
        /**
         * QuestionStatus
         * @enum {string}
         */
        QuestionStatus: "OK" | "ANSWER_REJECTED" | "ANSWER_UNAVAILABLE";
        /** Rebalancing */
        Rebalancing: {
            /** @description 강조 주기 M/Q/H. 필수 — FOCUS_INVALID. 계산은 세 주기 전부, 화면·AI에서 강조 */
            focus: components["schemas"]["Period"];
        };
        /** Risk */
        Risk: {
            /** Mdd Pct */
            mdd_pct: number;
            /** Vol Annual Pct */
            vol_annual_pct: number;
            /**
             * Worst Month Pct
             * @default null
             */
            worst_month_pct: number | null;
            /**
             * Max Drift Pct
             * @default null
             */
            max_drift_pct: number | null;
        };
        /** RiskClaim */
        RiskClaim: {
            /**
             * Title
             * @description 위험 요인 이름
             */
            title: string;
            /**
             * Detail
             * @description 이 위험이 뜻하는 바. 입력에 있는 값만 인용하고 직접 환산·계산하지 말 것
             */
            detail: string;
            /** Evidence */
            evidence: string[];
        };
        /** Sample */
        Sample: {
            /**
             * Id
             * @description P0 … (KAN-14 페르소나)
             */
            id: string;
            /** Label */
            label: string;
            inputs: components["schemas"]["PlanInputs"];
        };
        /** SamplesResponse */
        SamplesResponse: {
            /** Samples */
            samples: components["schemas"]["Sample"][];
        };
        /** Tax */
        Tax: {
            /**
             * Realized Cum
             * @default null
             */
            realized_cum: number | null;
            /**
             * Fv After Tax
             * @default null
             */
            fv_after_tax: number | null;
        };
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Month */
            month: number;
            /**
             * Invest
             * @default 0
             */
            invest: number;
            /**
             * Safe
             * @default 0
             */
            safe: number;
            /** Total */
            total: number;
        };
        /** UniverseAsset */
        UniverseAsset: {
            /**
             * Code
             * @description Kan-9 카탈로그 코드. portfolio.assets[].code 에 그대로 넣는다
             */
            code: string;
            /** Display Name */
            display_name: string;
            /**
             * Instrument
             * @description 종목코드 (069500 등)
             */
            instrument: string;
            /**
             * Group
             * @description base (KR_EQ·US_EQ·KR_BOND) | optional (US_EQ_KR)
             */
            group: string;
            /**
             * Tax Class
             * @default
             */
            tax_class: string;
        };
        /** UniverseResponse */
        UniverseResponse: {
            snapshot: components["schemas"]["UniverseSnapshot"];
            /** Assets */
            assets: components["schemas"]["UniverseAsset"][];
        };
        /**
         * UniverseSnapshot
         * @description 입력 폼에 노출할 데이터 기준. 필드명은 Kan-9 §5 `meta` 와 같게 — 프론트가 어휘 하나만 알면 되게.
         */
        UniverseSnapshot: {
            /** Data Version */
            data_version: string;
            /** Data Hash */
            data_hash: string;
            /**
             * Window
             * @description {start, end, months} — Kan-9 §5 meta.window 과 동일
             */
            window: {
                [key: string]: unknown;
            };
            /**
             * Safe Rate Annual Pct
             * @description 안전 버킷 예금금리 (연 %)
             */
            safe_rate_annual_pct: number;
        };
        /** Window */
        Window: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Months */
            months: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
